server:
  port: 50000

spring:
  datasource:
    url: jdbc:h2:mem:contact
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect